[project]
name = "vault-circle"
description = "VaultCircle public testnet manifest"
authors = []
telemetry = false
cache_dir = ".\\.cache"
requirements = []

[contracts.sip-010-ft-trait-v2]
path = "contracts/sip-010-ft-trait-v2.clar"
clarity_version = 3
epoch = "latest"

[contracts.governance-params-v2]
path = "contracts/governance-params-v2.clar"
clarity_version = 3
epoch = "latest"

[contracts.vault-registry-v2]
path = "contracts/vault-registry-v2.clar"
clarity_version = 3
epoch = "latest"

[contracts.zest-adapter-v2]
path = "contracts/zest-adapter-testnet-v2.clar"
clarity_version = 3
epoch = "latest"
depends_on = ["sip-010-ft-trait-v2"]

[contracts.proposal-manager-v2]
path = "contracts/proposal-manager-v2.clar"
clarity_version = 3
epoch = "latest"

[contracts.vault-circle-v2]
path = "contracts/vault-circle-v2.clar"
clarity_version = 3
epoch = "latest"
depends_on = ["sip-010-ft-trait-v2", "governance-params-v2", "vault-registry-v2", "proposal-manager-v2", "zest-adapter-v2"]

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = "https://api.hiro.so"
