export {
  APP_NETWORK,
  CONTRACT_IDS,
  CONTRACTS,
  DEFAULT_PROPOSAL_DURATION,
  DEPLOYER_ADDRESS,
  FRONTEND_ENV_WARNING,
  HAS_FRONTEND_ENV_FALLBACKS,
  PROTOCOL,
  STACKS_API_URL,
  STACKS_EXPLORER_URL,
  ZEST_MODE,
  getStacksNetwork,
  splitContractId
} from "./config";
